AT-8276-Page2-Security-Requirement-Component
dod-ccpo/atat-web-ui pull request #1171
Opened 2022-11-18 14:28 UTC by DGabriel-CCPO

In the event that the Mission Owner selects Secret and/or Top Secret in their classification requirements, the Mission Owner needs to input the security requirements that contractors will need to access. The Mission Owner also needs to input their need for a portability plan if they use Advisory and Assistance Services in Performance Requirements.

2022-11-18 18:42 UTC, ericyoungquist-ccpo requested changes

2022-11-18 18:42 UTC, ericyoungquist-ccpo commented on src/steps/04-ContractDetails/SecurityRequirements.vue
> +            <p id="SecretMessage" class="mb-5 font-weight-500">
update ID to `TopSecretMessage`

2022-11-18 18:42 UTC, ericyoungquist-ccpo commented on src/steps/04-ContractDetails/SecurityRequirements.vue
> +            <p id="SecretMessage" class="mb-5 ">
update ID to `TopSecretMessageNote`

2022-11-18 18:42 UTC, ericyoungquist-ccpo commented on src/steps/04-ContractDetails/SecurityRequirements.vue
> +              id="secretSecurityRequirements"
update ID to `TopSecretSecurityRequirements`

2022-11-18 18:42 UTC, ericyoungquist-ccpo commented on src/store/classificationRequirements/index.ts
> +  public async setCurrentENVClassificationLevels(value: ClassificationLevelDTO[]): Promise<void> {
pls delete this mutation - it was removed when current env classification requirements was refactored to be in the CurrentEnvironment store

2022-11-18 18:42 UTC, ericyoungquist-ccpo commented on src/store/classificationRequirements/index.ts
> +  public async setEnvironmentInstance(value: EnvironmentInstanceDTO[]): Promise<void> {
pls delete this mutation - it was removed when current env classification requirements was refactored to be in the CurrentEnvironment store

2022-11-18 18:44 UTC, ericyoungquist-ccpo commented on src/steps/04-ContractDetails/SecurityRequirements.vue
> +              id="secretSecurityRequirements"
PascalCase this ID pls

2022-11-20 15:38 UTC, ericyoungquist-ccpo requested changes

2022-11-20 15:38 UTC, ericyoungquist-ccpo commented on src/components/DOW/SecurityRequirementsCheckboxes.vue
> +        <v-col class="col-12">
remove `v-container` to `v-col` - adds unwanted padding

2022-11-20 15:38 UTC, ericyoungquist-ccpo commented on src/components/DOW/SecurityRequirementsForm.vue
> +        <v-col class="col-12">
remove `v-container` to `v-col` - adds unwanted padding

2022-11-22 22:26 UTC, tonysumner-ccpo approved these changes

2022-11-22 22:33 UTC, nkingsley-ccpo approved these changes

2022-11-22 22:33 UTC, merged