Feature/AT-6325 Vue E2E testing framework - nightwatch
dod-ccpo/atat-web-ui pull request #15
Opened 2021-07-06 17:48 UTC by jGonzalez-CCPO

Vue E2E testing framework - Evaluate option https://nightwatchjs.org/

Ticket: AT-6325

2021-07-07 18:53 UTC, jGonzalez-CCPO commented
e2e github action required credentials to be set on the environment.

2021-07-07 21:12 UTC, jasonburkert-ccpo requested changes
The file `browserstack_config/nightwatch.conf.js` is not being linted during `npm run lint`.  It is however being linted during GitHub check.

I suggest:
- change local linting to be more inclusive.  this file shouldn't be missed in its current location.
- perhaps move file `nightwatch.conf.js` to `tests`

2021-07-08 14:51 UTC, kylelaker-ccpo commented on tests/e2e/browserstack_config/nightwatch.conf.js
> +const chromedriver = require("chromedriver");
```suggestion
/* eslint-disable no-no-var-requires */
const path = require("path");
const deepmerge = require("deepmerge");
const chromedriver = require("chromedriver");
/* eslint-enable no-no-var-requires ​*/
```

Let's try this

2021-07-08 16:40 UTC, jGonzalez-CCPO commented on tests/e2e/.eslintrc.js
> +module.exports = {
@kylelaker-ccpo @jasonburkert-ccpo this file was generated by the vie-cli when I add Nightwatch maybe the problems is this is been ignore by github/super-linter@v4

2021-08-10 18:19 UTC, kylelaker-ccpo commented
@palaparthi-ccpo has taken over the work on this branch for the most part; I am going to close this particular PR so that a new one can be opened.

2021-08-10 18:19 UTC, closed without merging