AT-8782: Complete all functional requirements of this story except save to and load from snow
dod-ccpo/atat-web-ui pull request #1521
Opened 2023-04-24 20:06 UTC by ajaynalamala-ccpo

2023-04-24 23:55 UTC, ericyoungquist-ccpo requested changes

2023-04-24 23:55 UTC, ericyoungquist-ccpo commented on src/steps/02-EvaluationCriteria/JandA/DescriptionOfJustification.vue
> +          <p v-if="selectedException === 'YES_FAR_16_505_B_2_I_B'">
No logic in markup. Please use getters.

2023-04-24 23:55 UTC, ericyoungquist-ccpo commented on src/steps/02-EvaluationCriteria/JandA/DescriptionOfJustification.vue
> +            specialized capabilities” exception. Discuss the events, history, and
In all 3 cases, the vast majority of the text is exactly the same. Please use getters to fill in the blanks
```Briefly describe how this action requires use of the "_____" exception. Discuss the events, history, and circumstances that led to the current situation requiring use of procedures for other than fair opportunity competition. Your rationale should _____. ```

2023-04-24 23:55 UTC, ericyoungquist-ccpo commented on src/steps/02-EvaluationCriteria/JandA/DescriptionOfJustification.vue
> +                <ul>
Spacing is significantly off here (left is browser, right is Figma). Please add class "mb-4" to the `p` tag, and add class `_atat-ul` to the `ul` tag - it's a helper class we use to ensure correct list line spacing
<img width="488" alt="Screen Shot 2023-04-24 at 7 53 19 PM" src="https://user-images.githubusercontent.com/90333349/234139632-2dfa6e3f-4bb6-41f8-a9cc-fd73bcaf93a7.png">

2023-04-25 00:10 UTC, ericyoungquist-ccpo commented on src/steps/02-EvaluationCriteria/JandA/DescriptionOfJustification.vue
> +      // eslint-disable-next-line camelcase
remove this `eslint-disable` and one below - unnecessary here

2023-04-25 00:15 UTC, ericyoungquist-ccpo commented on src/steps/02-EvaluationCriteria/JandA/DescriptionOfJustification.vue
> +            <ATATExpandableLink aria-id="ContactFAQ2">
Update ID to relevant to this file

2023-04-25 15:23 UTC, tonysumner-ccpo approved these changes

2023-04-25 19:23 UTC, ericyoungquist-ccpo approved these changes

2023-04-25 19:23 UTC, merged