Feature/at 8846 J&A MRR 2.12 gather details about certification POCs
dod-ccpo/atat-web-ui pull request #1618
Opened 2023-05-18 14:55 UTC by ajaynalamala-ccpo

2023-05-18 19:01 UTC, ericyoungquist-ccpo requested changes

2023-05-18 19:01 UTC, ericyoungquist-ccpo commented on src/steps/02-EvaluationCriteria/MRR/CertificationPOCTypeForm.vue
> +        :roles.sync="contactRoles"
The Figma includes the field "Job Title" but does not include "Email address" for Civilian. For Military, the Figma still includes "Job Title" which I'm 99% sure is only bc the same component was used for the prototype. Will verify with Melissa or JC exactly which fields to include in both cases. 
![Screen Shot 2023-05-18 at 2 52 56 PM](https://github.com/dod-ccpo/atat-web-ui/assets/90333349/4b2127df-0e17-4418-ae3c-84292cfdf7b6)

2023-05-19 12:05 UTC, ajaynalamala-ccpo commented on src/components/ATATContactForm.vue
> +  private contactRoles: RadioButton[] = [ // Order reversed based on feedback provided on AT-8846
We will do a quick parking lot session and get to a consensus on this.

2023-05-19 18:57 UTC, ajaynalamala-ccpo commented on src/steps/02-EvaluationCriteria/MRR/CertificationPOCs.vue
> +    return true;
@ericyoungquist-ccpo We resolved the first 2 points during our huddle. And the last "ALSO has validation issue..." is working similar to the FinancialPOC.  After adding "await AcquisitionPackage.setValidateNow(true);" at the top of saveOnLeave, this behavior did not change and the user is able to Continue.

2023-05-22 19:11 UTC, ericyoungquist-ccpo requested changes

2023-05-22 19:11 UTC, ericyoungquist-ccpo commented on src/steps/02-EvaluationCriteria/MRR/CertificationPOCTypeForm.vue
> +          await AcquisitionPackage.setFairOpportunity(fairOpportunity)
These 3 lines (254-256) are exactly the same as the block above (249-451), which is almost exactly the same as the first block for checking if it's NEW, which the only difference is it first saves the new contact and then uses the savedContact's sys_id to save with `setFairOpportunity`. Please DRY this up.

2023-05-22 19:11 UTC, ericyoungquist-ccpo commented on src/components/ATATContactForm.vue
> +            id="JobTitle"
This and all other inputs (and anything with an `id`) will need to have unique `id`s and now that there are 2 instances of this form on the page, you'll need to pass a prop to either prepend or append a string that will make them unique.

2023-05-22 19:16 UTC, ericyoungquist-ccpo commented on src/steps/02-EvaluationCriteria/MRR/CertificationPOCTypeForm.vue
> +          this.selectedOption.value = savedContact.sys_id as string;
`this.selectedOption` is a getter. You can't set a value directly like this on a getter.

2023-05-24 12:00 UTC, ajaynalamala-ccpo commented on src/steps/02-EvaluationCriteria/MRR/CertificationPOCTypeForm.vue
> +          await AcquisitionPackage.setFairOpportunity(fairOpportunity)
Since we are not deleting the contacts, I can remove the "else if" block. And will further refactor this.

2023-05-24 15:36 UTC, ericyoungquist-ccpo requested changes

2023-05-24 15:36 UTC, ericyoungquist-ccpo commented on src/steps/02-EvaluationCriteria/MRR/CertificationPOCs.vue
> +    if (isValid) {
This doesn't work if 2nd child is valid but first is not.
https://github.com/dod-ccpo/atat-web-ui/assets/90333349/e56bb10e-31ee-457a-9ee3-89840dd14ad4

2023-05-24 15:41 UTC, ericyoungquist-ccpo commented
Please address sonarcloud code duplication

2023-05-24 22:22 UTC, ericyoungquist-ccpo commented on src/steps/02-EvaluationCriteria/MRR/CertificationPOCs.vue
> +    if (isValid) {
Validation to be completed in bug ticket related to Financial POC, COR/ACOR allowing continue without all required fields since uses same contact component as Financial POC page.

2023-05-24 22:25 UTC, ericyoungquist-ccpo commented on src/steps/02-EvaluationCriteria/MRR/CertificationPOCs.vue
> +    return true;
Validation to be addressed in future ticket with Financial POC since uses same contact form component.

2023-05-25 00:43 UTC, ericyoungquist-ccpo approved these changes

2023-05-25 00:44 UTC, ericyoungquist-ccpo commented
Sonarcloud code duplication issue appears to be a false positive.

2023-05-25 00:44 UTC, merged