feature/AT-9827-step8-reorder-substep-validations
dod-ccpo/atat-web-ui pull request #2017
Opened 2023-10-05 18:53 UTC by DGabriel-CCPO

AT-9781

2023-10-12 20:17 UTC, xanderkeele-ccpo requested changes
Couple changes before approval

2023-10-12 20:17 UTC, xanderkeele-ccpo commented on src/steps/10-FinancialDetails/IGCE/EstimatesDeveloped.spec.ts
> +    expect(str).toBe("underestimated");
New expectation does not match the test text "checks getter overUnderStr string 'overestimated'".

2023-10-12 20:17 UTC, xanderkeele-ccpo commented on src/steps/10-FinancialDetails/IGCE/EstimatesDeveloped.spec.ts
> +    expect(str).toBe("underestimated");
Something's wrong because this test passes and so does the next one.

2023-10-12 20:17 UTC, xanderkeele-ccpo commented on src/steps/10-FinancialDetails/IGCE/components/Card_Requirement.vue
> +          $validators.required(''),
Lines 50 and 51 need one more indent.

2023-10-13 17:06 UTC, davidpietrzak-ccpo approved these changes

2023-10-13 18:04 UTC, merged